# Generated by Django 5.2.4 on 2025-07-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("image", models.ImageField(upload_to="nail_img/")),
            ],
        ),
    ]
