# Generated by Django 5.2.4 on 2025-07-15 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nails", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nail",
            old_name="classification",
            new_name="nail_classification",
        ),
        migrations.RenameField(
            model_name="nail",
            old_name="image",
            new_name="nail_image",
        ),
    ]
