# Generated by Django 5.2.4 on 2025-07-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nails", "0002_rename_classification_nail_nail_classification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nail",
            name="confidence_level",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, max_length=10, null=True
            ),
        ),
    ]
